project_id = "lmqgndbiwgcpdbbvfbxm"

[functions.process-email-queue]
verify_jwt = true

[functions.ki-auswertung]
verify_jwt = false

[functions.send-lead-email]
verify_jwt = false

[functions.schedule-followup-emails]
verify_jwt = false

[functions.handle-unsubscribe]
verify_jwt = false