/**
 * Auto-Generator für public/sitemap.xml.
 * SSOT: scripts/seo-routes.ts (ROUTES). Routen mit `noindex: true` werden ausgelassen.
 *
 * Wird vor jedem `vite dev` (predev) und `vite build` (prebuild) ausgeführt.
 * Neue Blog-Artikel oder Routen → einfach in ROUTES eintragen, sitemap aktualisiert sich automatisch.
 */
import { writeFileSync } from "fs";
import { resolve } from "path";
import { ROUTES, BASE_URL, type SeoRoute } from "./seo-routes";

interface SitemapEntry {
  path: string;
  lastmod: string;
  changefreq: "weekly" | "monthly" | "yearly";
  priority: string;
}

const TODAY = new Date().toISOString().slice(0, 10);

function defaultsFor(route: SeoRoute): Omit<SitemapEntry, "path"> {
  const p = route.path;
  if (p === "/") return { lastmod: TODAY, changefreq: "weekly", priority: "1.0" };
  if (p === "/blog") return { lastmod: TODAY, changefreq: "weekly", priority: "0.8" };
  if (p.startsWith("/blog/")) return { lastmod: TODAY, changefreq: "monthly", priority: "0.8" };
  if (p === "/rentenluecken-rechner" || p === "/altersvorsorgedepot")
    return { lastmod: TODAY, changefreq: "monthly", priority: "0.95" };
  if (p === "/einbetten") return { lastmod: TODAY, changefreq: "yearly", priority: "0.4" };
  if (p === "/newsletter") return { lastmod: TODAY, changefreq: "monthly", priority: "0.7" };
  return { lastmod: TODAY, changefreq: "monthly", priority: "0.85" };
}

const entries: SitemapEntry[] = ROUTES.filter((r) => !r.noindex).map((r) => ({
  path: r.path,
  ...defaultsFor(r),
}));

const xml = [
  `<?xml version="1.0" encoding="UTF-8"?>`,
  `<!-- Auto-generated by scripts/generate-sitemap.ts. DO NOT EDIT BY HAND. -->`,
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">`,
  ...entries.map((e) =>
    [
      `  <url>`,
      `    <loc>${BASE_URL}${e.path}</loc>`,
      `    <lastmod>${e.lastmod}</lastmod>`,
      `    <changefreq>${e.changefreq}</changefreq>`,
      `    <priority>${e.priority}</priority>`,
      `  </url>`,
    ].join("\n"),
  ),
  `</urlset>`,
  ``,
].join("\n");

writeFileSync(resolve("public/sitemap.xml"), xml);
console.log(`✅ sitemap.xml geschrieben (${entries.length} Einträge)`);
